  services:
  reception:
    image: reception
    build:
      context: .
      dockerfile: reception/Dockerfile
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reception