version: '3.8'

services:
  reception:
    image: service-reception
    container_name: reception-service
    build:
      context: .
      dockerfile: reception/Dockerfile
    ports:
      - "8080:8080"
      - "5084:5084"
    networks:
      - net_storage

networks:
  net_storage:
    name: net_storage
    external: true
