version: '3.8'
  
services:
  reception:
    image: reception
    container_name: reception-compose
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "5084:5084"
    networks:
      - net_storage
  
networks:
  net_storage:
    name: net_storage
    external: true
